defaults: &defaults
  STRIPE_KEY:            '123'
  STRIPE_PUBLIC_KEY:     '456'
  COMPANY_NAME: 'Megacorp'
  username: 'thenapster',
  password: 'swordfish'


development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
